### ISSUE TITLE
Missing async-mutex module

### ISSUE THREAD

**Issue by jkurland-roku** [matts1/bazel-rust-analyzer#2]
I've been getting this error trying to run this extension

```
2024-08-19 11:22:07.440 [error] Activating extension MattStark.bazel-rust-analyzer failed due to an error:
2024-08-19 11:22:07.440 [error] Error: Cannot find module 'async-mutex'
Require stack:
- /home/jkurland/.vscode-server/extensions/mattstark.bazel-rust-analyzer-0.0.1/out/gen_rust_project.js
- /home/jkurland/.vscode-server/extensions/mattstark.bazel-rust-analyzer-0.0.1/out/extension.js
- /home/jkurland/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/bootstrap-fork.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
	at Module._load (node:internal/modules/cjs/loader:986:27)
	at y._load (/home/jkurland/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/workbench/api/node/extensionHostProcess.js:177:6051)
	at i._load (/home/jkurland/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/workbench/api/node/extensionHostProcess.js:174:31787)
	at o._load (/home/jkurland/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/workbench/api/node/extensionHostProcess.js:139:34334)
	at Module.require (node:internal/modules/cjs/loader:1233:19)
	at require (node:internal/modules/helpers:179:18)
	at Object.<anonymous> (/home/jkurland/.vscode-server/extensions/mattstark.bazel-rust-analyzer-0.0.1/out/gen_rust_project.js:5:23)
	at Module._compile (node:internal/modules/cjs/loader:1358:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
	at Module.load (node:internal/modules/cjs/loader:1208:32)
	at Module._load (node:internal/modules/cjs/loader:1024:12)
	at y._load (/home/jkurland/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/workbench/api/node/extensionHostProcess.js:177:6051)
	at i._load (/home/jkurland/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/workbench/api/node/extensionHostProcess.js:174:31787)
	at o._load (/home/jkurland/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/workbench/api/node/extensionHostProcess.js:139:34334)
	at Module.require (node:internal/modules/cjs/loader:1233:19)
	at require (node:internal/modules/helpers:179:18)
	at Object.<anonymous> (/home/jkurland/.vscode-server/extensions/mattstark.bazel-rust-analyzer-0.0.1/out/extension.js:5:28)
	at Module._compile (node:internal/modules/cjs/loader:1358:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
	at Module.load (node:internal/modules/cjs/loader:1208:32)
	at Module._load (node:internal/modules/cjs/loader:1024:12)
	at y._load (/home/jkurland/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/workbench/api/node/extensionHostProcess.js:177:6051)
	at i._load (/home/jkurland/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/workbench/api/node/extensionHostProcess.js:174:31787)
	at o._load (/home/jkurland/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/workbench/api/node/extensionHostProcess.js:139:34334)
	at Module.require (node:internal/modules/cjs/loader:1233:19)
	at require (node:internal/modules/helpers:179:18)
	at Function.i [as __$__nodeRequire] (/home/jkurland/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/bootstrap-fork.js:3:98)
	at m.xb (/home/jkurland/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/vs/workbench/api/node/extensionHostProcess.js:174:32966)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 0)
```

**Comment by jkurland-roku** [comment]
As a workaround I ran "npm install" in the extension directory (e.g. ~/.vscode/extensions/mattstark.bazel-rust-analyzer-0.0.1) and that seemed to work
